apiVersion: batch/v1
kind: Job
metadata:
  name: at-glry-job
spec:
  template:
    spec:
      containers:
      - name: at-glry-job
        image: yash5090/at-glry:latest
        ports:
        - containerPort: 5000
      restartPolicy: OnFailure
