apiVersion: apps/v1
kind: Deployment
metadata:
  name: at-glry-deployment
spec:
  replicas: 6 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: at-glry
  template:
    metadata:
      labels:
        app: at-glry
    spec:
      containers:
        - name: at-glry
          image: yash5090/at-glry:latest # Replace with the actual image tag
          ports:
            - containerPort: 5000 # Replace with the port your Tetris game listens on
